"""
Constantes del sistema.

NO contiene cuentas contables hardcodeadas.
Las cuentas se obtienen de accounting_parameter_value.

Este archivo solo contiene:
- Codigos de modulo
- Codigos de evento
- Codigos de parametro
- Codigos de tipo de documento
"""
# ─── Modulos del ERP ───
MOD_ADMIN = 'admin'
MOD_CONTABILIDAD = 'contabilidad'
MOD_BANCOS = 'bancos'
MOD_CXC = 'cxc'
MOD_CXP = 'cxp'
MOD_COMPRAS = 'compras'
MOD_FACTURACION = 'facturacion'
MOD_INVENTARIO = 'inventario'
MOD_ACTIVOS_FIJOS = 'activos_fijos'
MOD_NOMINA = 'nomina'
MOD_PRESUPUESTOS = 'presupuestos'

# ─── Codigos de Parametros Contables ───
PARAM_VENTAS_CONTADO = 'VENTAS_CONTADO'
PARAM_VENTAS_CREDITO = 'VENTAS_CREDITO'
PARAM_IVA_DEBITO = 'IVA_DEBITO'
PARAM_IVA_CREDITO = 'IVA_CREDITO'
PARAM_DESCUENTOS_VENTA = 'DESCUENTOS_VENTA'
PARAM_CXC_CLIENTES = 'CXC_CLIENTES'
PARAM_CXP_PROVEEDORES = 'CXP_PROVEEDORES'
PARAM_INVENTARIO_MERCANCIAS = 'INVENTARIO_MERCANCIAS'
PARAM_COSTO_VENTAS = 'COSTO_VENTAS'
PARAM_CAJA_GENERAL = 'CAJA_GENERAL'
PARAM_BANCO_CUENTA = 'BANCO_CUENTA'
PARAM_COMPRAS_NAC = 'COMPRAS_NACIONALES'
PARAM_COMPRAS_IMP = 'COMPRAS_IMPORTACION'
PARAM_RETENCION_IR = 'RETENCION_IR'
PARAM_RETENCION_IVA = 'RETENCION_IVA'
PARAM_CONSUMO_PROPIO = 'CONSUMO_PROPIO_CUENTA'
PARAM_ACTIVO_FIJO = 'ACTIVO_FIJO'
PARAM_DEPRECIACION_ACUM = 'DEPRECIACION_ACUMULADA'
PARAM_GASTO_DEPRECIACION = 'GASTO_DEPRECIACION'
PARAM_SUELDOS = 'SUELDOS'
PARAM_INSS_PATRONAL = 'INSS_PATRONAL'
PARAM_INSS_LABORAL = 'INSS_LABORAL'
PARAM_IR_EMPLEADOS = 'IR_EMPLEADOS'

# ─── Eventos de Negocio ───
EVENT_COMPRA_REGISTRADA = 'COMPRA_REGISTRADA'
EVENT_ENTRADA_INVENTARIO = 'ENTRADA_INVENTARIO'
EVENT_FACTURA_EMITIDA = 'FACTURA_EMITIDA'
EVENT_SALIDA_INVENTARIO = 'SALIDA_INVENTARIO'
EVENT_COBRO_RECIBIDO = 'COBRO_RECIBIDO'
EVENT_PAGO_REALIZADO = 'PAGO_REALIZADO'
EVENT_RETENCION_APLICADA = 'RETENCION_APLICADA'
EVENT_AJUSTE_POSITIVO = 'AJUSTE_POSITIVO'
EVENT_AJUSTE_NEGATIVO = 'AJUSTE_NEGATIVO'
EVENT_CONSUMO_PROPIO = 'CONSUMO_PROPIO'
EVENT_TRASLADO_BODEGA = 'TRASLADO_BODEGA'
EVENT_REVERSION_DOCUMENTO = 'REVERSION_DOCUMENTO'
EVENT_DEPRECIACION_CONT = 'DEPRECIACION_CONTABILIZADA'
EVENT_NOMINA_CONTABILIZADA = 'NOMINA_CONTABILIZADA'
EVENT_CIERRE_PERIODO = 'CIERRE_PERIODO'

# ─── Tipos de Documento ───
DOC_FACTURA = 'FAC'
DOC_NOTA_CREDITO = 'NCR'
DOC_NOTA_DEBITO = 'NDB'
DOC_ORDEN_COMPRA = 'OC'
DOC_RECEPCION = 'RECEPCION'
DOC_COBRO = 'COBRO'
DOC_PAGO = 'PAGO'
DOC_RETENCION = 'RET'
DOC_CHEQUE = 'CHEQUE'
DOC_TRANSFERENCIA = 'TRANSFERENCIA'
DOC_DEBITO_BANCARIO = 'DEBITO'
DOC_CREDITO_BANCARIO = 'CREDITO'
DOC_ENTRADA_INVENTARIO = 'ENTRADA'
DOC_SALIDA_INVENTARIO = 'SALIDA'
DOC_AJUSTE_INVENTARIO = 'AJUSTE'
DOC_TRASLADO = 'TRASLADO'
DOC_DEPRECIACION = 'DEPRECIACION'
DOC_NOMINA = 'NOMINA'
DOC_PRESUPUESTO = 'PRESUPUESTO'

# ─── Estados de Documento ───
EST_BORRADOR = 'BORRADOR'
EST_PENDIENTE = 'PENDIENTE'
EST_PENDIENTE_APROBACION = 'PENDIENTE_APROBACION'
EST_APROBADO = 'APROBADO'
EST_RECHAZADO = 'RECHAZADO'
EST_CONTABILIZADO = 'CONTABILIZADO'
EST_PAGADO = 'PAGADO'
EST_COBRADO = 'COBRADO'
EST_ANULADO = 'ANULADO'
EST_REVERSADO = 'REVERSADO'
EST_CERRADO = 'CERRADO'

# ─── Acciones de Workflow ───
ACT_CREAR = 'CREAR'
ACT_EMITIR = 'EMITIR'
ACT_APROBAR = 'APROBAR'
ACT_RECHAZAR = 'RECHAZAR'
ACT_CONTABILIZAR = 'CONTABILIZAR'
ACT_ANULAR = 'ANULAR'
ACT_REVERTIR = 'REVERTIR'
ACT_PAGAR = 'PAGAR'
ACT_COBRAR = 'COBRAR'
ACT_CERRAR = 'CERRAR'
ACT_REABRIR = 'REABRIR'
