declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'
  type Icon = FC<SVGProps<SVGSVGElement>>
  export const LayoutDashboard: Icon
  export const BarChart3: Icon
  export const PiggyBank: Icon
  export const TrendingUp: Icon
  export const ArrowRightLeft: Icon
  export const Users: Icon
  export const Truck: Icon
  export const Database: Icon
  export const ShoppingCart: Icon
  export const Building2: Icon
  export const FileText: Icon
  export const Settings: Icon
  export const BookOpen: Icon
  export const Shield: Icon
  export const X: Icon
  export const Search: Icon
  export const ChevronDown: Icon
  export const ChevronRight: Icon
  export const UserCheck: Icon
  export const DollarSign: Icon
  export const CreditCard: Icon
  export const Receipt: Icon
  export const Wallet: Icon
  export const Briefcase: Icon
  export const Calculator: Icon
  export const Globe: Icon
  export const HardDrive: Icon
  export const Menu: Icon
  export const Download: Icon
  export const Plus: Icon
  export const Edit3: Icon
  export const Trash2: Icon
  export const Check: Icon
  export const AlertTriangle: Icon
  export const Loader2: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const LogOut: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ChevronUp: Icon
  export const Home: Icon
  export const Info: Icon
  export const AlertCircle: Icon
  export const CheckCircle: Icon
  export const ArrowUpDown: Icon
  export const ArrowUp: Icon
  export const ArrowDown: Icon
  export const Filter: Icon
  export const RefreshCw: Icon
  export const Printer: Icon
  export const Upload: Icon
  export const Image: Icon
  export const Camera: Icon
  export const Calendar: Icon
  export const Clock: Icon
  export const Bell: Icon
  export const Mail: Icon
  export const Phone: Icon
  export const MapPin: Icon
  export const Lock: Icon
  export const Unlock: Icon
  export const Key: Icon
  export const Scale: Icon
  export const Save: Icon
  export const Send: Icon
  export const Share2: Icon
  export const MoreHorizontal: Icon
  export const MoreVertical: Icon
  export const ExternalLink: Icon
  export const Link: Icon
  export const Copy: Icon
  export const ClipboardList: Icon
  export const ClipboardCheck: Icon
  export const List: Icon
  export const Grid: Icon
  export const Table: Icon
  export const Type: Icon
  export const Bold: Icon
  export const Italic: Icon
  export const Underline: Icon
  export const Hash: Icon
  export const Percent: Icon
  export const Minus: Icon
  export const Divide: Icon
  export const Equal: Icon
  export const NotEqual: Icon
  export const FolderOpen: Icon
  export const BadgePercent: Icon
  export const CalendarDays: Icon
  export const Banknote: Icon
  export const GripVertical: Icon
  export const PanelLeft: Icon
  export const PanelRight: Icon
  export const PanelBottom: Icon
  export const PanelTop: Icon
}
